# Site settings
title: WebJeda | A modern web development blog
description: "WebJeda is a company oriented towards building modern websites and apps. It also provides smart hosting solutions"
url: http://blog.webjeda.com
author:
  name: "Sharath Kumar"
  email: "info@redgadgets.com"
  url: "http://www.webjeda.com.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
gems:
  - jekyll-sitemap
  
#optimization
sass:
    style: :compressed
    
    
authors:
      sharathdt:
        display_name: sharath.dt
        gravatar: https://raw.githubusercontent.com/sharu725/lanyon/gh-pages/public/img/sharathdt.jpeg
        email: mailto:info@dxartist.com
        web: http://webjeda.com/
        facebook: https://www.facebook.com/sharu725
        twitter: https://twitter.com/sharathdt
        github: sharu725
