# Site settings
title: Emerald | A simple Jekyll blog
description: "A minimal blog template, build with Jekyll."


# Build settings
baseurl: /blog.pegadadelixo.com.br/
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
